translating
LCTT/LCRH pull request #125
Opened 2020-11-01 13:53 UTC by KeaneQy

2020-11-01 23:16 UTC, Northurland requested changes
建议对长句进行进一步拆分，以使译文更符合中文语言习惯。例如，中文中通常没有较长的从句，所以遇到从句可以将其拆分出来单独作为一句。
同样地，也可以在语序不符合中文表达习惯时对其进行更改，只要译文总体的意思和原文相同即可。

2020-11-05 17:27 UTC, wxy commented
@Northurland 顺便说一句，这个 PR 的提交比较多，建议在最终接受时，squash and merge。

2020-11-20 10:55 UTC, wxy commented
@KeaneQy 这篇还需加工一下。

2020-12-03 04:31 UTC, wxy approved these changes

2020-12-03 04:32 UTC, merged